web:
  build: .
  command: /bin/bash -c "cd app && python network_of_innovators.py -b 0.0.0.0:8000 -D --pid gunicorn.pid --error-logfile gunicorn-err.log noi_server:app"
  links:
    - db
  ports:
    - "80:8080"
  volumes:
    - ./:/noi
  environment:
    NOI_PORT: 8080
  ports:
    - "80:8080"
db:
  image: postgres:9.4
